import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Provider from "./Provider";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "G-SMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        <Provider>
          <main className="py-20 max-w-7xl mx-auto">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
